name: Generate Metrics

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC
  workflow_dispatch:      # Also allow manual run

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rzilient-club
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Paris
          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_languages_threshold: 1%
          plugin_stars: yes
          plugin_topics: yes
