name: 🧠 GitHub Metrics (Split Output)

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  main-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rzilient-club
          template: classic
          config_timezone: Europe/Paris

          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_languages_threshold: 1%
          plugin_stars: yes
          plugin_topics: yes
          plugin_traffic: yes
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14

          config_output: metrics.svg

  isometric-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rzilient-club
          template: classic
          config_timezone: Europe/Paris

          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          config_output: isometric-calendar.svg
