name: Org Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  org-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rzilient-club
          template: classic
          base: repositories
          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_languages_threshold: 1%
          plugin_stars: yes
          plugin_topics: yes
          plugin_traffic: yes
